version: '3'

services:
  postgres:
    image: postgres:14.10
    container_name: scaler_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - scaler:/var/lib/postgresql/data
volumes:
  scaler: